#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBSGRH_ERP")]

public partial class ERPManagementRHDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  partial void InserttEmpleado(tEmpleado instance);
  partial void UpdatetEmpleado(tEmpleado instance);
  partial void DeletetEmpleado(tEmpleado instance);
  partial void InserttUsuarios(tUsuarios instance);
  partial void UpdatetUsuarios(tUsuarios instance);
  partial void DeletetUsuarios(tUsuarios instance);
  partial void InserttCorreoElectronicoEmpleado(tCorreoElectronicoEmpleado instance);
  partial void UpdatetCorreoElectronicoEmpleado(tCorreoElectronicoEmpleado instance);
  partial void DeletetCorreoElectronicoEmpleado(tCorreoElectronicoEmpleado instance);
  partial void InsertcEmpresas(cEmpresas instance);
  partial void UpdatecEmpresas(cEmpresas instance);
  partial void DeletecEmpresas(cEmpresas instance);
  partial void InsertcGrupo(cGrupo instance);
  partial void UpdatecGrupo(cGrupo instance);
  partial void DeletecGrupo(cGrupo instance);
  #endregion
	
	public ERPManagementRHDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DBRHConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public ERPManagementRHDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ERPManagementRHDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ERPManagementRHDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ERPManagementRHDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tEmpleado> tEmpleado
	{
		get
		{
			return this.GetTable<tEmpleado>();
		}
	}
	
	public System.Data.Linq.Table<tUsuarios> tUsuarios
	{
		get
		{
			return this.GetTable<tUsuarios>();
		}
	}
	
	public System.Data.Linq.Table<tCorreoElectronicoEmpleado> tCorreoElectronicoEmpleado
	{
		get
		{
			return this.GetTable<tCorreoElectronicoEmpleado>();
		}
	}
	
	public System.Data.Linq.Table<vUsuarioAcceso> vUsuarioAcceso
	{
		get
		{
			return this.GetTable<vUsuarioAcceso>();
		}
	}
	
	public System.Data.Linq.Table<view_ValidarTipoUsuarioAreaGrupo> view_ValidarTipoUsuarioAreaGrupo
	{
		get
		{
			return this.GetTable<view_ValidarTipoUsuarioAreaGrupo>();
		}
	}
	
	public System.Data.Linq.Table<cEmpresas> cEmpresas
	{
		get
		{
			return this.GetTable<cEmpresas>();
		}
	}
	
	public System.Data.Linq.Table<cGrupo> cGrupo
	{
		get
		{
			return this.GetTable<cGrupo>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tEmpleado")]
public partial class tEmpleado : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idEmpleado;
	
	private string _nombre;
	
	private string _apellidoPaterno;
	
	private string _apellidoMaterno;
	
	private string _sexo;
	
	private System.Nullable<System.DateTime> _fechaNacimiento;
	
	private string _curp;
	
	private string _rfc;
	
	private string _nss;
	
	private int _idEstadoCivil;
	
	private string _seguroVida;
	
	private string _estadoSalud;
	
	private string _tipoSangre;
	
	private string _visa;
	
	private string _pasaporte;
	
	private System.Nullable<System.DateTime> _fechaIngreso;
	
	private System.Nullable<System.DateTime> _fechaFin;
	
	private System.Nullable<int> _idEmpresa;
	
	private System.Nullable<int> _idPuesto;
	
	private System.Nullable<int> _idArea;
	
	private System.Nullable<int> _idNacionalidad;
	
	private System.Nullable<int> _idDomicilio;
	
	private System.Nullable<int> _idUbicacion;
	
	private System.Nullable<bool> _critico;
	
	private System.Nullable<System.DateTime> _fechaContrato;
	
	private System.Nullable<int> _idGerente;
	
	private System.Nullable<int> _idReligion;
	
	private EntitySet<tCorreoElectronicoEmpleado> _tCorreoElectronicoEmpleado;
	
	private EntityRef<cEmpresas> _cEmpresas;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEmpleadoChanging(int value);
    partial void OnidEmpleadoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoPaternoChanging(string value);
    partial void OnapellidoPaternoChanged();
    partial void OnapellidoMaternoChanging(string value);
    partial void OnapellidoMaternoChanged();
    partial void OnsexoChanging(string value);
    partial void OnsexoChanged();
    partial void OnfechaNacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaNacimientoChanged();
    partial void OncurpChanging(string value);
    partial void OncurpChanged();
    partial void OnrfcChanging(string value);
    partial void OnrfcChanged();
    partial void OnnssChanging(string value);
    partial void OnnssChanged();
    partial void OnidEstadoCivilChanging(int value);
    partial void OnidEstadoCivilChanged();
    partial void OnseguroVidaChanging(string value);
    partial void OnseguroVidaChanged();
    partial void OnestadoSaludChanging(string value);
    partial void OnestadoSaludChanged();
    partial void OntipoSangreChanging(string value);
    partial void OntipoSangreChanged();
    partial void OnvisaChanging(string value);
    partial void OnvisaChanged();
    partial void OnpasaporteChanging(string value);
    partial void OnpasaporteChanged();
    partial void OnfechaIngresoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaIngresoChanged();
    partial void OnfechaFinChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaFinChanged();
    partial void OnidEmpresaChanging(System.Nullable<int> value);
    partial void OnidEmpresaChanged();
    partial void OnidPuestoChanging(System.Nullable<int> value);
    partial void OnidPuestoChanged();
    partial void OnidAreaChanging(System.Nullable<int> value);
    partial void OnidAreaChanged();
    partial void OnidNacionalidadChanging(System.Nullable<int> value);
    partial void OnidNacionalidadChanged();
    partial void OnidDomicilioChanging(System.Nullable<int> value);
    partial void OnidDomicilioChanged();
    partial void OnidUbicacionChanging(System.Nullable<int> value);
    partial void OnidUbicacionChanged();
    partial void OncriticoChanging(System.Nullable<bool> value);
    partial void OncriticoChanged();
    partial void OnfechaContratoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaContratoChanged();
    partial void OnidGerenteChanging(System.Nullable<int> value);
    partial void OnidGerenteChanged();
    partial void OnidReligionChanging(System.Nullable<int> value);
    partial void OnidReligionChanged();
    #endregion
	
	public tEmpleado()
	{
		this._tCorreoElectronicoEmpleado = new EntitySet<tCorreoElectronicoEmpleado>(new Action<tCorreoElectronicoEmpleado>(this.attach_tCorreoElectronicoEmpleado), new Action<tCorreoElectronicoEmpleado>(this.detach_tCorreoElectronicoEmpleado));
		this._cEmpresas = default(EntityRef<cEmpresas>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idEmpleado
	{
		get
		{
			return this._idEmpleado;
		}
		set
		{
			if ((this._idEmpleado != value))
			{
				this.OnidEmpleadoChanging(value);
				this.SendPropertyChanging();
				this._idEmpleado = value;
				this.SendPropertyChanged("idEmpleado");
				this.OnidEmpleadoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(30)")]
	public string nombre
	{
		get
		{
			return this._nombre;
		}
		set
		{
			if ((this._nombre != value))
			{
				this.OnnombreChanging(value);
				this.SendPropertyChanging();
				this._nombre = value;
				this.SendPropertyChanged("nombre");
				this.OnnombreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidoPaterno", DbType="VarChar(30)")]
	public string apellidoPaterno
	{
		get
		{
			return this._apellidoPaterno;
		}
		set
		{
			if ((this._apellidoPaterno != value))
			{
				this.OnapellidoPaternoChanging(value);
				this.SendPropertyChanging();
				this._apellidoPaterno = value;
				this.SendPropertyChanged("apellidoPaterno");
				this.OnapellidoPaternoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidoMaterno", DbType="VarChar(30)")]
	public string apellidoMaterno
	{
		get
		{
			return this._apellidoMaterno;
		}
		set
		{
			if ((this._apellidoMaterno != value))
			{
				this.OnapellidoMaternoChanging(value);
				this.SendPropertyChanging();
				this._apellidoMaterno = value;
				this.SendPropertyChanged("apellidoMaterno");
				this.OnapellidoMaternoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="VarChar(1)")]
	public string sexo
	{
		get
		{
			return this._sexo;
		}
		set
		{
			if ((this._sexo != value))
			{
				this.OnsexoChanging(value);
				this.SendPropertyChanging();
				this._sexo = value;
				this.SendPropertyChanged("sexo");
				this.OnsexoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNacimiento", DbType="DateTime")]
	public System.Nullable<System.DateTime> fechaNacimiento
	{
		get
		{
			return this._fechaNacimiento;
		}
		set
		{
			if ((this._fechaNacimiento != value))
			{
				this.OnfechaNacimientoChanging(value);
				this.SendPropertyChanging();
				this._fechaNacimiento = value;
				this.SendPropertyChanged("fechaNacimiento");
				this.OnfechaNacimientoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curp", DbType="VarChar(18)")]
	public string curp
	{
		get
		{
			return this._curp;
		}
		set
		{
			if ((this._curp != value))
			{
				this.OncurpChanging(value);
				this.SendPropertyChanging();
				this._curp = value;
				this.SendPropertyChanged("curp");
				this.OncurpChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rfc", DbType="VarChar(20)")]
	public string rfc
	{
		get
		{
			return this._rfc;
		}
		set
		{
			if ((this._rfc != value))
			{
				this.OnrfcChanging(value);
				this.SendPropertyChanging();
				this._rfc = value;
				this.SendPropertyChanged("rfc");
				this.OnrfcChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nss", DbType="VarChar(15)")]
	public string nss
	{
		get
		{
			return this._nss;
		}
		set
		{
			if ((this._nss != value))
			{
				this.OnnssChanging(value);
				this.SendPropertyChanging();
				this._nss = value;
				this.SendPropertyChanged("nss");
				this.OnnssChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstadoCivil", DbType="Int NOT NULL")]
	public int idEstadoCivil
	{
		get
		{
			return this._idEstadoCivil;
		}
		set
		{
			if ((this._idEstadoCivil != value))
			{
				this.OnidEstadoCivilChanging(value);
				this.SendPropertyChanging();
				this._idEstadoCivil = value;
				this.SendPropertyChanged("idEstadoCivil");
				this.OnidEstadoCivilChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seguroVida", DbType="VarChar(50)")]
	public string seguroVida
	{
		get
		{
			return this._seguroVida;
		}
		set
		{
			if ((this._seguroVida != value))
			{
				this.OnseguroVidaChanging(value);
				this.SendPropertyChanging();
				this._seguroVida = value;
				this.SendPropertyChanged("seguroVida");
				this.OnseguroVidaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estadoSalud", DbType="VarChar(10)")]
	public string estadoSalud
	{
		get
		{
			return this._estadoSalud;
		}
		set
		{
			if ((this._estadoSalud != value))
			{
				this.OnestadoSaludChanging(value);
				this.SendPropertyChanging();
				this._estadoSalud = value;
				this.SendPropertyChanged("estadoSalud");
				this.OnestadoSaludChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoSangre", DbType="VarChar(20)")]
	public string tipoSangre
	{
		get
		{
			return this._tipoSangre;
		}
		set
		{
			if ((this._tipoSangre != value))
			{
				this.OntipoSangreChanging(value);
				this.SendPropertyChanging();
				this._tipoSangre = value;
				this.SendPropertyChanged("tipoSangre");
				this.OntipoSangreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visa", DbType="VarChar(20)")]
	public string visa
	{
		get
		{
			return this._visa;
		}
		set
		{
			if ((this._visa != value))
			{
				this.OnvisaChanging(value);
				this.SendPropertyChanging();
				this._visa = value;
				this.SendPropertyChanged("visa");
				this.OnvisaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pasaporte", DbType="VarChar(20)")]
	public string pasaporte
	{
		get
		{
			return this._pasaporte;
		}
		set
		{
			if ((this._pasaporte != value))
			{
				this.OnpasaporteChanging(value);
				this.SendPropertyChanging();
				this._pasaporte = value;
				this.SendPropertyChanged("pasaporte");
				this.OnpasaporteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaIngreso", DbType="Date")]
	public System.Nullable<System.DateTime> fechaIngreso
	{
		get
		{
			return this._fechaIngreso;
		}
		set
		{
			if ((this._fechaIngreso != value))
			{
				this.OnfechaIngresoChanging(value);
				this.SendPropertyChanging();
				this._fechaIngreso = value;
				this.SendPropertyChanged("fechaIngreso");
				this.OnfechaIngresoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaFin", DbType="Date")]
	public System.Nullable<System.DateTime> fechaFin
	{
		get
		{
			return this._fechaFin;
		}
		set
		{
			if ((this._fechaFin != value))
			{
				this.OnfechaFinChanging(value);
				this.SendPropertyChanging();
				this._fechaFin = value;
				this.SendPropertyChanged("fechaFin");
				this.OnfechaFinChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpresa", DbType="Int")]
	public System.Nullable<int> idEmpresa
	{
		get
		{
			return this._idEmpresa;
		}
		set
		{
			if ((this._idEmpresa != value))
			{
				if (this._cEmpresas.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnidEmpresaChanging(value);
				this.SendPropertyChanging();
				this._idEmpresa = value;
				this.SendPropertyChanged("idEmpresa");
				this.OnidEmpresaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPuesto", DbType="Int")]
	public System.Nullable<int> idPuesto
	{
		get
		{
			return this._idPuesto;
		}
		set
		{
			if ((this._idPuesto != value))
			{
				this.OnidPuestoChanging(value);
				this.SendPropertyChanging();
				this._idPuesto = value;
				this.SendPropertyChanged("idPuesto");
				this.OnidPuestoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idArea", DbType="Int")]
	public System.Nullable<int> idArea
	{
		get
		{
			return this._idArea;
		}
		set
		{
			if ((this._idArea != value))
			{
				this.OnidAreaChanging(value);
				this.SendPropertyChanging();
				this._idArea = value;
				this.SendPropertyChanged("idArea");
				this.OnidAreaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNacionalidad", DbType="Int")]
	public System.Nullable<int> idNacionalidad
	{
		get
		{
			return this._idNacionalidad;
		}
		set
		{
			if ((this._idNacionalidad != value))
			{
				this.OnidNacionalidadChanging(value);
				this.SendPropertyChanging();
				this._idNacionalidad = value;
				this.SendPropertyChanged("idNacionalidad");
				this.OnidNacionalidadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDomicilio", DbType="Int")]
	public System.Nullable<int> idDomicilio
	{
		get
		{
			return this._idDomicilio;
		}
		set
		{
			if ((this._idDomicilio != value))
			{
				this.OnidDomicilioChanging(value);
				this.SendPropertyChanging();
				this._idDomicilio = value;
				this.SendPropertyChanged("idDomicilio");
				this.OnidDomicilioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUbicacion", DbType="Int")]
	public System.Nullable<int> idUbicacion
	{
		get
		{
			return this._idUbicacion;
		}
		set
		{
			if ((this._idUbicacion != value))
			{
				this.OnidUbicacionChanging(value);
				this.SendPropertyChanging();
				this._idUbicacion = value;
				this.SendPropertyChanged("idUbicacion");
				this.OnidUbicacionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_critico", DbType="Bit")]
	public System.Nullable<bool> critico
	{
		get
		{
			return this._critico;
		}
		set
		{
			if ((this._critico != value))
			{
				this.OncriticoChanging(value);
				this.SendPropertyChanging();
				this._critico = value;
				this.SendPropertyChanged("critico");
				this.OncriticoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaContrato", DbType="Date")]
	public System.Nullable<System.DateTime> fechaContrato
	{
		get
		{
			return this._fechaContrato;
		}
		set
		{
			if ((this._fechaContrato != value))
			{
				this.OnfechaContratoChanging(value);
				this.SendPropertyChanging();
				this._fechaContrato = value;
				this.SendPropertyChanged("fechaContrato");
				this.OnfechaContratoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idGerente", DbType="Int")]
	public System.Nullable<int> idGerente
	{
		get
		{
			return this._idGerente;
		}
		set
		{
			if ((this._idGerente != value))
			{
				this.OnidGerenteChanging(value);
				this.SendPropertyChanging();
				this._idGerente = value;
				this.SendPropertyChanged("idGerente");
				this.OnidGerenteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idReligion", DbType="Int")]
	public System.Nullable<int> idReligion
	{
		get
		{
			return this._idReligion;
		}
		set
		{
			if ((this._idReligion != value))
			{
				this.OnidReligionChanging(value);
				this.SendPropertyChanging();
				this._idReligion = value;
				this.SendPropertyChanged("idReligion");
				this.OnidReligionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tEmpleado_tCorreoElectronicoEmpleado", Storage="_tCorreoElectronicoEmpleado", ThisKey="idEmpleado", OtherKey="idEmpleado")]
	public EntitySet<tCorreoElectronicoEmpleado> tCorreoElectronicoEmpleado
	{
		get
		{
			return this._tCorreoElectronicoEmpleado;
		}
		set
		{
			this._tCorreoElectronicoEmpleado.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cEmpresas_tEmpleado", Storage="_cEmpresas", ThisKey="idEmpresa", OtherKey="idEmpresa", IsForeignKey=true)]
	public cEmpresas cEmpresas
	{
		get
		{
			return this._cEmpresas.Entity;
		}
		set
		{
			cEmpresas previousValue = this._cEmpresas.Entity;
			if (((previousValue != value) 
						|| (this._cEmpresas.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._cEmpresas.Entity = null;
					previousValue.tEmpleado.Remove(this);
				}
				this._cEmpresas.Entity = value;
				if ((value != null))
				{
					value.tEmpleado.Add(this);
					this._idEmpresa = value.idEmpresa;
				}
				else
				{
					this._idEmpresa = default(Nullable<int>);
				}
				this.SendPropertyChanged("cEmpresas");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tCorreoElectronicoEmpleado(tCorreoElectronicoEmpleado entity)
	{
		this.SendPropertyChanging();
		entity.tEmpleado = this;
	}
	
	private void detach_tCorreoElectronicoEmpleado(tCorreoElectronicoEmpleado entity)
	{
		this.SendPropertyChanging();
		entity.tEmpleado = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tUsuarios")]
public partial class tUsuarios : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idUsuario;
	
	private string _usuario;
	
	private string _contrasena;
	
	private System.Nullable<int> _idEstatusUsuario;
	
	private System.Nullable<int> _idTipoUsuario;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OncontrasenaChanging(string value);
    partial void OncontrasenaChanged();
    partial void OnidEstatusUsuarioChanging(System.Nullable<int> value);
    partial void OnidEstatusUsuarioChanged();
    partial void OnidTipoUsuarioChanging(System.Nullable<int> value);
    partial void OnidTipoUsuarioChanged();
    #endregion
	
	public tUsuarios()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int idUsuario
	{
		get
		{
			return this._idUsuario;
		}
		set
		{
			if ((this._idUsuario != value))
			{
				this.OnidUsuarioChanging(value);
				this.SendPropertyChanging();
				this._idUsuario = value;
				this.SendPropertyChanged("idUsuario");
				this.OnidUsuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(MAX)")]
	public string usuario
	{
		get
		{
			return this._usuario;
		}
		set
		{
			if ((this._usuario != value))
			{
				this.OnusuarioChanging(value);
				this.SendPropertyChanging();
				this._usuario = value;
				this.SendPropertyChanged("usuario");
				this.OnusuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasena", DbType="VarChar(MAX)")]
	public string contrasena
	{
		get
		{
			return this._contrasena;
		}
		set
		{
			if ((this._contrasena != value))
			{
				this.OncontrasenaChanging(value);
				this.SendPropertyChanging();
				this._contrasena = value;
				this.SendPropertyChanged("contrasena");
				this.OncontrasenaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstatusUsuario", DbType="Int")]
	public System.Nullable<int> idEstatusUsuario
	{
		get
		{
			return this._idEstatusUsuario;
		}
		set
		{
			if ((this._idEstatusUsuario != value))
			{
				this.OnidEstatusUsuarioChanging(value);
				this.SendPropertyChanging();
				this._idEstatusUsuario = value;
				this.SendPropertyChanged("idEstatusUsuario");
				this.OnidEstatusUsuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoUsuario", DbType="Int")]
	public System.Nullable<int> idTipoUsuario
	{
		get
		{
			return this._idTipoUsuario;
		}
		set
		{
			if ((this._idTipoUsuario != value))
			{
				this.OnidTipoUsuarioChanging(value);
				this.SendPropertyChanging();
				this._idTipoUsuario = value;
				this.SendPropertyChanged("idTipoUsuario");
				this.OnidTipoUsuarioChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tCorreoElectronicoEmpleado")]
public partial class tCorreoElectronicoEmpleado : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idTipoCorreoElectronico;
	
	private int _idEmpleado;
	
	private string _correoElectronico;
	
	private EntityRef<tEmpleado> _tEmpleado;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTipoCorreoElectronicoChanging(int value);
    partial void OnidTipoCorreoElectronicoChanged();
    partial void OnidEmpleadoChanging(int value);
    partial void OnidEmpleadoChanged();
    partial void OncorreoElectronicoChanging(string value);
    partial void OncorreoElectronicoChanged();
    #endregion
	
	public tCorreoElectronicoEmpleado()
	{
		this._tEmpleado = default(EntityRef<tEmpleado>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoCorreoElectronico", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int idTipoCorreoElectronico
	{
		get
		{
			return this._idTipoCorreoElectronico;
		}
		set
		{
			if ((this._idTipoCorreoElectronico != value))
			{
				this.OnidTipoCorreoElectronicoChanging(value);
				this.SendPropertyChanging();
				this._idTipoCorreoElectronico = value;
				this.SendPropertyChanged("idTipoCorreoElectronico");
				this.OnidTipoCorreoElectronicoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int idEmpleado
	{
		get
		{
			return this._idEmpleado;
		}
		set
		{
			if ((this._idEmpleado != value))
			{
				if (this._tEmpleado.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnidEmpleadoChanging(value);
				this.SendPropertyChanging();
				this._idEmpleado = value;
				this.SendPropertyChanged("idEmpleado");
				this.OnidEmpleadoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correoElectronico", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string correoElectronico
	{
		get
		{
			return this._correoElectronico;
		}
		set
		{
			if ((this._correoElectronico != value))
			{
				this.OncorreoElectronicoChanging(value);
				this.SendPropertyChanging();
				this._correoElectronico = value;
				this.SendPropertyChanged("correoElectronico");
				this.OncorreoElectronicoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tEmpleado_tCorreoElectronicoEmpleado", Storage="_tEmpleado", ThisKey="idEmpleado", OtherKey="idEmpleado", IsForeignKey=true)]
	public tEmpleado tEmpleado
	{
		get
		{
			return this._tEmpleado.Entity;
		}
		set
		{
			tEmpleado previousValue = this._tEmpleado.Entity;
			if (((previousValue != value) 
						|| (this._tEmpleado.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tEmpleado.Entity = null;
					previousValue.tCorreoElectronicoEmpleado.Remove(this);
				}
				this._tEmpleado.Entity = value;
				if ((value != null))
				{
					value.tCorreoElectronicoEmpleado.Add(this);
					this._idEmpleado = value.idEmpleado;
				}
				else
				{
					this._idEmpleado = default(int);
				}
				this.SendPropertyChanged("tEmpleado");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vUsuarioAcceso")]
public partial class vUsuarioAcceso
{
	
	private int _idUsuario;
	
	private string _nombre;
	
	private string _apellidoPaterno;
	
	private string _apellidoMaterno;
	
	private string _usuario;
	
	private string _contrasena;
	
	private string _correoElectronico;
	
	private System.Nullable<int> _idEstatusUsuario;
	
	public vUsuarioAcceso()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
	public int idUsuario
	{
		get
		{
			return this._idUsuario;
		}
		set
		{
			if ((this._idUsuario != value))
			{
				this._idUsuario = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(30)")]
	public string nombre
	{
		get
		{
			return this._nombre;
		}
		set
		{
			if ((this._nombre != value))
			{
				this._nombre = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidoPaterno", DbType="VarChar(30)")]
	public string apellidoPaterno
	{
		get
		{
			return this._apellidoPaterno;
		}
		set
		{
			if ((this._apellidoPaterno != value))
			{
				this._apellidoPaterno = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidoMaterno", DbType="VarChar(30)")]
	public string apellidoMaterno
	{
		get
		{
			return this._apellidoMaterno;
		}
		set
		{
			if ((this._apellidoMaterno != value))
			{
				this._apellidoMaterno = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(MAX)")]
	public string usuario
	{
		get
		{
			return this._usuario;
		}
		set
		{
			if ((this._usuario != value))
			{
				this._usuario = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasena", DbType="VarChar(MAX)")]
	public string contrasena
	{
		get
		{
			return this._contrasena;
		}
		set
		{
			if ((this._contrasena != value))
			{
				this._contrasena = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correoElectronico", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string correoElectronico
	{
		get
		{
			return this._correoElectronico;
		}
		set
		{
			if ((this._correoElectronico != value))
			{
				this._correoElectronico = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstatusUsuario", DbType="Int")]
	public System.Nullable<int> idEstatusUsuario
	{
		get
		{
			return this._idEstatusUsuario;
		}
		set
		{
			if ((this._idEstatusUsuario != value))
			{
				this._idEstatusUsuario = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_ValidarTipoUsuarioAreaGrupo")]
public partial class view_ValidarTipoUsuarioAreaGrupo
{
	
	private int _idUsuario;
	
	private System.Nullable<int> _idTipoUsuario;
	
	private string _grupo;
	
	private string _idGrupo;
	
	private string _area;
	
	private string _idArea;
	
	public view_ValidarTipoUsuarioAreaGrupo()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
	public int idUsuario
	{
		get
		{
			return this._idUsuario;
		}
		set
		{
			if ((this._idUsuario != value))
			{
				this._idUsuario = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoUsuario", DbType="Int")]
	public System.Nullable<int> idTipoUsuario
	{
		get
		{
			return this._idTipoUsuario;
		}
		set
		{
			if ((this._idTipoUsuario != value))
			{
				this._idTipoUsuario = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grupo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string grupo
	{
		get
		{
			return this._grupo;
		}
		set
		{
			if ((this._grupo != value))
			{
				this._grupo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idGrupo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string idGrupo
	{
		get
		{
			return this._idGrupo;
		}
		set
		{
			if ((this._idGrupo != value))
			{
				this._idGrupo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string area
	{
		get
		{
			return this._area;
		}
		set
		{
			if ((this._area != value))
			{
				this._area = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idArea", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string idArea
	{
		get
		{
			return this._idArea;
		}
		set
		{
			if ((this._idArea != value))
			{
				this._idArea = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cEmpresas")]
public partial class cEmpresas : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _idEmpresa;
	
	private string _descripcion;
	
	private int _id_grupo;
	
	private string _rfc;
	
	private System.Nullable<int> _id_contacto;
	
	private string _logotipo;
	
	private EntitySet<tEmpleado> _tEmpleado;
	
	private EntityRef<cGrupo> _cGrupo;
	
	private EntityRef<cGrupo> _cGrupo1;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEmpresaChanging(int value);
    partial void OnidEmpresaChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Onid_grupoChanging(int value);
    partial void Onid_grupoChanged();
    partial void OnrfcChanging(string value);
    partial void OnrfcChanged();
    partial void Onid_contactoChanging(System.Nullable<int> value);
    partial void Onid_contactoChanged();
    partial void OnlogotipoChanging(string value);
    partial void OnlogotipoChanged();
    #endregion
	
	public cEmpresas()
	{
		this._tEmpleado = new EntitySet<tEmpleado>(new Action<tEmpleado>(this.attach_tEmpleado), new Action<tEmpleado>(this.detach_tEmpleado));
		this._cGrupo = default(EntityRef<cGrupo>);
		this._cGrupo1 = default(EntityRef<cGrupo>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpresa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int idEmpresa
	{
		get
		{
			return this._idEmpresa;
		}
		set
		{
			if ((this._idEmpresa != value))
			{
				this.OnidEmpresaChanging(value);
				this.SendPropertyChanging();
				this._idEmpresa = value;
				this.SendPropertyChanged("idEmpresa");
				this.OnidEmpresaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string descripcion
	{
		get
		{
			return this._descripcion;
		}
		set
		{
			if ((this._descripcion != value))
			{
				this.OndescripcionChanging(value);
				this.SendPropertyChanging();
				this._descripcion = value;
				this.SendPropertyChanged("descripcion");
				this.OndescripcionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_grupo", DbType="Int NOT NULL")]
	public int id_grupo
	{
		get
		{
			return this._id_grupo;
		}
		set
		{
			if ((this._id_grupo != value))
			{
				if ((this._cGrupo.HasLoadedOrAssignedValue || this._cGrupo1.HasLoadedOrAssignedValue))
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_grupoChanging(value);
				this.SendPropertyChanging();
				this._id_grupo = value;
				this.SendPropertyChanged("id_grupo");
				this.Onid_grupoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rfc", DbType="VarChar(MAX)")]
	public string rfc
	{
		get
		{
			return this._rfc;
		}
		set
		{
			if ((this._rfc != value))
			{
				this.OnrfcChanging(value);
				this.SendPropertyChanging();
				this._rfc = value;
				this.SendPropertyChanged("rfc");
				this.OnrfcChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_contacto", DbType="Int")]
	public System.Nullable<int> id_contacto
	{
		get
		{
			return this._id_contacto;
		}
		set
		{
			if ((this._id_contacto != value))
			{
				this.Onid_contactoChanging(value);
				this.SendPropertyChanging();
				this._id_contacto = value;
				this.SendPropertyChanged("id_contacto");
				this.Onid_contactoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logotipo", DbType="VarChar(MAX)")]
	public string logotipo
	{
		get
		{
			return this._logotipo;
		}
		set
		{
			if ((this._logotipo != value))
			{
				this.OnlogotipoChanging(value);
				this.SendPropertyChanging();
				this._logotipo = value;
				this.SendPropertyChanged("logotipo");
				this.OnlogotipoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cEmpresas_tEmpleado", Storage="_tEmpleado", ThisKey="idEmpresa", OtherKey="idEmpresa")]
	public EntitySet<tEmpleado> tEmpleado
	{
		get
		{
			return this._tEmpleado;
		}
		set
		{
			this._tEmpleado.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cGrupo_cEmpresas", Storage="_cGrupo", ThisKey="id_grupo", OtherKey="id_grupo", IsForeignKey=true)]
	public cGrupo cGrupo
	{
		get
		{
			return this._cGrupo.Entity;
		}
		set
		{
			cGrupo previousValue = this._cGrupo.Entity;
			if (((previousValue != value) 
						|| (this._cGrupo.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._cGrupo.Entity = null;
					previousValue.cEmpresas.Remove(this);
				}
				this._cGrupo.Entity = value;
				if ((value != null))
				{
					value.cEmpresas.Add(this);
					this._id_grupo = value.id_grupo;
				}
				else
				{
					this._id_grupo = default(int);
				}
				this.SendPropertyChanged("cGrupo");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cGrupo_cEmpresas1", Storage="_cGrupo1", ThisKey="id_grupo", OtherKey="id_grupo", IsForeignKey=true)]
	public cGrupo cGrupo1
	{
		get
		{
			return this._cGrupo1.Entity;
		}
		set
		{
			cGrupo previousValue = this._cGrupo1.Entity;
			if (((previousValue != value) 
						|| (this._cGrupo1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._cGrupo1.Entity = null;
					previousValue.cEmpresas1.Remove(this);
				}
				this._cGrupo1.Entity = value;
				if ((value != null))
				{
					value.cEmpresas1.Add(this);
					this._id_grupo = value.id_grupo;
				}
				else
				{
					this._id_grupo = default(int);
				}
				this.SendPropertyChanged("cGrupo1");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tEmpleado(tEmpleado entity)
	{
		this.SendPropertyChanging();
		entity.cEmpresas = this;
	}
	
	private void detach_tEmpleado(tEmpleado entity)
	{
		this.SendPropertyChanging();
		entity.cEmpresas = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cGrupo")]
public partial class cGrupo : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_grupo;
	
	private string _grupo;
	
	private EntitySet<cEmpresas> _cEmpresas;
	
	private EntitySet<cEmpresas> _cEmpresas1;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_grupoChanging(int value);
    partial void Onid_grupoChanged();
    partial void OngrupoChanging(string value);
    partial void OngrupoChanged();
    #endregion
	
	public cGrupo()
	{
		this._cEmpresas = new EntitySet<cEmpresas>(new Action<cEmpresas>(this.attach_cEmpresas), new Action<cEmpresas>(this.detach_cEmpresas));
		this._cEmpresas1 = new EntitySet<cEmpresas>(new Action<cEmpresas>(this.attach_cEmpresas1), new Action<cEmpresas>(this.detach_cEmpresas1));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_grupo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_grupo
	{
		get
		{
			return this._id_grupo;
		}
		set
		{
			if ((this._id_grupo != value))
			{
				this.Onid_grupoChanging(value);
				this.SendPropertyChanging();
				this._id_grupo = value;
				this.SendPropertyChanged("id_grupo");
				this.Onid_grupoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grupo", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string grupo
	{
		get
		{
			return this._grupo;
		}
		set
		{
			if ((this._grupo != value))
			{
				this.OngrupoChanging(value);
				this.SendPropertyChanging();
				this._grupo = value;
				this.SendPropertyChanged("grupo");
				this.OngrupoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cGrupo_cEmpresas", Storage="_cEmpresas", ThisKey="id_grupo", OtherKey="id_grupo")]
	public EntitySet<cEmpresas> cEmpresas
	{
		get
		{
			return this._cEmpresas;
		}
		set
		{
			this._cEmpresas.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cGrupo_cEmpresas1", Storage="_cEmpresas1", ThisKey="id_grupo", OtherKey="id_grupo")]
	public EntitySet<cEmpresas> cEmpresas1
	{
		get
		{
			return this._cEmpresas1;
		}
		set
		{
			this._cEmpresas1.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_cEmpresas(cEmpresas entity)
	{
		this.SendPropertyChanging();
		entity.cGrupo = this;
	}
	
	private void detach_cEmpresas(cEmpresas entity)
	{
		this.SendPropertyChanging();
		entity.cGrupo = null;
	}
	
	private void attach_cEmpresas1(cEmpresas entity)
	{
		this.SendPropertyChanging();
		entity.cGrupo1 = this;
	}
	
	private void detach_cEmpresas1(cEmpresas entity)
	{
		this.SendPropertyChanging();
		entity.cGrupo1 = null;
	}
}
#pragma warning restore 1591
